language: node_js
matrix:
  include:
    - node_js: "4"
    - node_js: "5"
    - node_js: "6"

script: "make test-travis"
after_script: "npm install coveralls@2.11.1 && cat ./coverage/lcov.info | coveralls"
